version: 0.0
os: linux
files:
  - source: /
    destination: /opt/tonkotsu-nodejs/
hooks:
  BeforeInstall:
    - location: deploy/before_install/before_start.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/before_install/after_start.sh
      timeout: 300
      runas: root
