version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    - image: circleci/postgres:9.6.3-alpine
      environment:
        POSTGRES_USER: root
        POSTGRES_DB: circle_test
    steps:
    - checkout
    - run: echo "Hello CircleCI!"
workflows:
  version: 2
  workflow:
    jobs:
    - build
