name: scp copy folder to remote via SSH

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
        
     
          
      - name: ls -a via ssh1
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /opt/tonkotsu-nodejs
            ll
          host: 13.229.147.148
          username: root
          password: github@2020
        env:
          CI: true
        
    
