name: scp copy folder to remote via SSH

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
        
      - name: Copy folder content recursively to remote
        uses: ./
        with:
          local: "dist"
          remote: "/opt/tonkotsu-nodejs"
          host: 13.229.147.148
          username: root
          password: github@2020
        env:
          CI: true
