name: scp copy folder to remote via SSH

on:
  push

jobs:
  linux:
    name: Linux build on node v12.16.2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10.x, 12.x]

    steps:
      - name: checkout
        uses: actions/checkout@v1
        
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: "."
          remote: "/opt/tonkotsu-nodejs"
          host: 13.229.147.148
          username: root
          password: github@2020
        env:
          CI: true
          
      - name: Set Node.js version 5
        uses: actions/setup-node@v1
        with:
           node-version: v12.16.2
          
      - name: Install packages
        run: npm install
      - name: Run build
        run: npm start
        
        env:
          CI: true
        
