name: scp copy folder to remote via SSH

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
        
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: "."
          remote: "/opt/tonkotsu-nodejs"
          host: 13.229.147.148
          username: root
          password: github@2020
        env:
          CI: true
          
      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /opt/tonkotsu-nodejs
            
            npm start
          host: 13.229.147.148
          username: root
          password: github@2020
        env:
          CI: true
        
