# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - github-group6webapp(staging)

on:
  push:
    branches:
      - nasha2878-challenge4

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'github-group6webapp(staging)'
        slot-name: 'staging'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5b85ef1660b14e44bfa54233b58b1814 }}
        package: .