# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ${{matrix.os-type}}

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        os-type: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name : nmp install, build, and test
      run:
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: team1testapp
        publish-profile: team1testapp(staging).publishsettings
        slot-name: staging
